### ISSUE TITLE
Avoid using x as a variable name. 

### ISSUE THREAD

**Issue by cnangeh** [Mimi97-aqua/Python-Scratch-Projects#3]
Give a meaningful name. like guess_number or something

https://github.com/Mimi97-aqua/Python-Scratch-Projects/blob/15c9ab625c471f056f54be5ca88092e74437821b/guessingGame.py#L23

**Comment by Mimi97-aqua** [comment]
The variable name **x** has been changed to **randomNumber**

**Comment by cnangeh** [comment]
Already resolved. Change was push directly to master branch
